title: Digital Design Methods
description: The official site of __Digital Design Methods__

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
